Repository StockmonGo/BE, pull requests merged in 2024-09, with the labels that each got.

#28 [FEAT] Swagger 세팅 및 API 리팩토링
  core/src/main/java/com/pda/core/controller/AccountController.java
  core/src/main/java/com/pda/core/controller/SwaggerTestController.java
  core/src/main/java/com/pda/core/controller/TravelerController.java
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/controller/WorldController.java
  core/src/main/resources/application.properties
  stock/src/main/resources/application.properties
Labels: :recycle: refactor, ✨ Feature

#30 [Feat] 스톡타워 보상 요청 api 구현 #26
  core/src/main/java/com/pda/core/controller/AccountController.java
  core/src/main/java/com/pda/core/controller/StockTowerTimerController.java
  core/src/main/java/com/pda/core/dto/StockTowerTimerRequestDto.java
  core/src/main/java/com/pda/core/dto/StockTowerTimerResponseDto.java
  core/src/main/java/com/pda/core/dto/StockTowerTimerUpdateDto.java
  core/src/main/java/com/pda/core/entity/StockTowerTimer.java
  core/src/main/java/com/pda/core/exception/CoolDownException.java
  core/src/main/java/com/pda/core/exception/ExceptionMessage.java
  core/src/main/java/com/pda/core/repository/RedisRepository.java
  core/src/main/java/com/pda/core/repository/StockTowerTimerRepository.java
  core/src/main/java/com/pda/core/service/StockTowerTimerService.java
Labels: ✨ Feature

#31 [Feat] 회원가입/로그인/회원탈퇴 API 추가
  build.gradle
  commons/src/main/java/com/pda/commons/swagger/SwaggerConfig.java
  core/src/main/java/com/pda/core/config/AppConfig.java
  core/src/main/java/com/pda/core/config/SecurityConfig.java
  core/src/main/java/com/pda/core/config/SwaggerConfig.java
  core/src/main/java/com/pda/core/controller/AccountController.java
  core/src/main/java/com/pda/core/controller/TravelerController.java
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/controller/WorldController.java
  core/src/main/java/com/pda/core/dto/CreateAccountRequestDto.java
  core/src/main/java/com/pda/core/dto/CustomUserDetailDto.java
  core/src/main/java/com/pda/core/dto/GetWorldStockmonsRequestDto.java
  core/src/main/java/com/pda/core/dto/JoinRequestDto.java
  core/src/main/java/com/pda/core/dto/JoinResponseDto.java
  core/src/main/java/com/pda/core/dto/SignInRequestDto.java
  core/src/main/java/com/pda/core/dto/TravelerStockmonDto.java
  core/src/main/java/com/pda/core/entity/Traveler.java
  core/src/main/java/com/pda/core/exception/DuplicateTravelerException.java
  core/src/main/java/com/pda/core/exception/ExceptionMessage.java
  core/src/main/java/com/pda/core/exception/HasAccountException.java
  core/src/main/java/com/pda/core/exception/NoStockmonDetailException.java
  core/src/main/java/com/pda/core/exception/NoTravelerException.java
  core/src/main/java/com/pda/core/exception/RequestBodyException.java
  core/src/main/java/com/pda/core/exception/UserNamePasswordException.java
  core/src/main/java/com/pda/core/repository/TravelerRepository.java
  core/src/main/java/com/pda/core/security/LoginFilter.java
  core/src/main/java/com/pda/core/service/AccountService.java
  core/src/main/java/com/pda/core/service/CustomUserDetailService.java
  core/src/main/java/com/pda/core/service/StockTowerService.java
  core/src/main/java/com/pda/core/service/StockmonService.java
  core/src/main/java/com/pda/core/service/TravelerService.java
  core/src/main/java/com/pda/core/service/WorldService.java
  core/src/main/java/com/pda/core/utils/JwtUtil.java
  core/src/main/java/com/pda/core/utils/RandomUtil.java
  core/src/main/java/com/pda/core/utils/WorldConstant.java
  core/src/main/resources/application.properties
Labels: :recycle: refactor, ✨ Feature

#33 [Feat] stocktower detail 구현 #32
  core/src/main/java/com/pda/core/controller/StockTowerTimerController.java
  core/src/main/java/com/pda/core/dto/StockTowerTimerDetailResponseDto.java
  core/src/main/java/com/pda/core/exception/CoreException.java
  core/src/main/java/com/pda/core/exception/CoreExceptionHandler.java
  core/src/main/java/com/pda/core/exception/ExceptionMessage.java
  core/src/main/java/com/pda/core/exception/HasAccountException.java
  core/src/main/java/com/pda/core/exception/NoStockTowerException.java
  core/src/main/java/com/pda/core/exception/NoTravelerException.java
  core/src/main/java/com/pda/core/exception/RequestBodyException.java
  core/src/main/java/com/pda/core/exception/UserNamePasswordException.java
  core/src/main/java/com/pda/core/repository/StockTowerTimerRepository.java
  core/src/main/java/com/pda/core/service/StockTowerTimerService.java
Labels: ✨ Feature

#35 [Feat] HTTPS 구현
  core/src/main/java/com/pda/core/config/SwaggerConfig.java
Labels: ✨ Feature

#39 [FIX] Traveler_Stockmon이 제대로 조회되지 않는 에러
  core/src/main/java/com/pda/core/config/SwaggerConfig.java
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/repository/StockmonRepository.java
  core/src/main/java/com/pda/core/service/StockmonService.java
Labels: 🐛 fix

#40 [Feat] AllianceNotice, TravelerNotice 엔티티 추가 및 날짜 관련 컬럼 삭제
  .gitignore
  core/src/main/java/com/pda/core/entity/Alliance.java
  core/src/main/java/com/pda/core/entity/AllianceNotice.java
  core/src/main/java/com/pda/core/entity/ExchangeNotice.java
Labels: ✨ Feature

#42 [Feat] 스톡몬 교환 요청 API #41
  core/src/main/java/com/pda/core/controller/ExchangeNoticeController.java
  core/src/main/java/com/pda/core/dto/StockmonExchangeNoticeRequestDto.java
  core/src/main/java/com/pda/core/dto/StockmonExchangeNoticeResponseDto.java
  core/src/main/java/com/pda/core/entity/ExchangeNotice.java
  core/src/main/java/com/pda/core/entity/Stockmon.java
  core/src/main/java/com/pda/core/entity/Traveler.java
  core/src/main/java/com/pda/core/repository/ExchangeNoticeRepository.java
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
Labels: ✨ Feature

#44 [Feat] 남은 스톡볼 개수 조회 기능 구현 #43
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/dto/GetTravelerStockballsResponseDto.java
  core/src/main/java/com/pda/core/repository/TravelerRepository.java
  core/src/main/java/com/pda/core/service/TravelerService.java
Labels: ✨ Feature

#46 [Feat] 동맹 조회 API 구현 #29
  core/src/main/java/com/pda/core/controller/AllianceController.java
  core/src/main/java/com/pda/core/repository/AllianceRepository.java
  core/src/main/java/com/pda/core/service/AllianceService.java
Labels: ✨ Feature

#47 [Fix] 스톡타워 보상 요청 api 수정 #45
  core/src/main/java/com/pda/core/controller/StockTowerTimerController.java
  core/src/main/java/com/pda/core/entity/Traveler.java
  core/src/main/java/com/pda/core/service/StockTowerTimerService.java
Labels: 🐛 fix

#50 [Feat] OpenFeign으로 Core와 Stock 연결
  build.gradle
  core/src/main/java/com/pda/core/CoreApplication.java
  core/src/main/java/com/pda/core/client/StockFeignClient.java
  core/src/main/java/com/pda/core/config/FeignConfig.java
  core/src/main/java/com/pda/core/controller/AllianceController.java
  core/src/main/java/com/pda/core/controller/SwaggerTestController.java
  core/src/main/java/com/pda/core/dto/GetStockmonDetailResponseDto.java
  core/src/main/java/com/pda/core/dto/alliance/AllianceDto.java
  core/src/main/java/com/pda/core/dto/alliance/GetTravelerAllianceListResponseDto.java
  core/src/main/java/com/pda/core/dto/alliance/TravelerAllianceDto.java
  core/src/main/java/com/pda/core/repository/AllianceRepository.java
  core/src/main/java/com/pda/core/service/AllianceService.java
  core/src/main/java/com/pda/core/service/StockmonService.java
  stock/src/main/java/com/pda/stock/StockApplication.java
  stock/src/main/java/com/pda/stock/client/KISFeignClient.java
  stock/src/main/java/com/pda/stock/config/FeignConfig.java
  stock/src/main/java/com/pda/stock/controller/KISController.java
  stock/src/main/java/com/pda/stock/controller/TestController.java
  stock/src/main/java/com/pda/stock/dto/StockInfoDto.java
  stock/src/main/java/com/pda/stock/service/KISService.java
  stock/src/main/java/com/pda/stock/websocket/WebSocketEventListener.java
  stock/src/main/resources/application.properties
Labels: ✨ Feature, 🐛 fix

#51 [Feat] 스톡몬 교환 요청 리스트 조회 api 구현 #49
  build.gradle
  core/src/main/java/com/pda/core/client/StockFeignClient.java
  core/src/main/java/com/pda/core/controller/ExchangeNoticeController.java
  core/src/main/java/com/pda/core/dto/GetStockmonExchangeListResponseDto.java
  core/src/main/java/com/pda/core/repository/ExchangeNoticeRepository.java
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
Labels: ✨ Feature, 🐛 fix

#54 [Feat] 스톡몬 교환 요청 수락 api 구현 #52
  core/src/main/java/com/pda/core/controller/ExchangeNoticeController.java
  core/src/main/java/com/pda/core/dto/AcceptStockmonExchangeRequestDto.java
  core/src/main/java/com/pda/core/dto/AcceptStockmonExchangeResponseDto.java
  core/src/main/java/com/pda/core/entity/TravelerStockmon.java
  core/src/main/java/com/pda/core/exception/InvalidExchangeRequestException.java
  core/src/main/java/com/pda/core/exception/InvalidNoticeIdOrReceiverException.java
  core/src/main/java/com/pda/core/exception/NoStockmonException.java
  core/src/main/java/com/pda/core/repository/ExchangeNoticeRepository.java
  core/src/main/java/com/pda/core/repository/TravelerStockmonRepository.java
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
Labels: ✨ Feature

#57 [Feat] 캐치 기능 추가 및 코드 합치기
  core/src/main/java/com/pda/core/client/StockFeignClient.java
  core/src/main/java/com/pda/core/controller/AllianceController.java
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/dto/CatchStockmonRequestDto.java
  core/src/main/java/com/pda/core/dto/CatchStockmonResponseDto.java
  core/src/main/java/com/pda/core/dto/WorldStockmonDto.java
  core/src/main/java/com/pda/core/entity/TravelerStockmon.java
  core/src/main/java/com/pda/core/entity/World.java
  core/src/main/java/com/pda/core/exception/InvalidStockballCountException.java
  core/src/main/java/com/pda/core/exception/NoStockmonException.java
  core/src/main/java/com/pda/core/repository/TravelerAllianceRepository.java
  core/src/main/java/com/pda/core/repository/TravelerRepository.java
  core/src/main/java/com/pda/core/repository/TravelerStockmonRepository.java
  core/src/main/java/com/pda/core/service/AllianceService.java
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
  core/src/main/java/com/pda/core/service/TravelerStockmonService.java
  core/src/main/java/com/pda/core/service/WorldService.java
  core/src/main/resources/application.properties
  stock/src/main/java/com/pda/stock/controller/KISController.java
Labels: ✨ Feature

#58 [Feat] 스톡몬 교환 요청 거절 기능 구현 #55
  core/src/main/java/com/pda/core/controller/ExchangeNoticeController.java
  core/src/main/java/com/pda/core/dto/RejectStockmonExchangeRequestDto.java
  core/src/main/java/com/pda/core/repository/ExchangeNoticeRepository.java
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
Labels: ✨ Feature

#60 [Fix] 스톡몬 교환 요청 관련 createdAt 컬럼 추가 및 엔티티 반영 #59
  core/src/main/java/com/pda/core/dto/GetStockmonExchangeListResponseDto.java
  core/src/main/java/com/pda/core/dto/StockmonExchangeNoticeRequestDto.java
  core/src/main/java/com/pda/core/entity/ExchangeNotice.java
  core/src/main/java/com/pda/core/repository/ExchangeNoticeRepository.java
Labels: 🐛 fix, 🔧 chore

#62 [Refactor] 소켓 기반 STOMP 소켓 세션 관리, 데이터 전송 성능 최적화 및 cors 설정 수정
  stock/src/main/java/com/pda/stock/StockApplication.java
  stock/src/main/java/com/pda/stock/config/WebConfig.java
  stock/src/main/java/com/pda/stock/controller/StockController.java
  stock/src/main/java/com/pda/stock/websocket/CustomHandshakeHandler.java
  stock/src/main/java/com/pda/stock/websocket/WebSocketConfig.java
  stock/src/main/java/com/pda/stock/websocket/WebSocketEventListener.java
Labels: :recycle: refactor

#66 [Feat] 차트 API 구현
  core/src/main/java/com/pda/core/controller/TravelerController.java
  stock/src/main/java/com/pda/stock/client/KISFeignClient.java
  stock/src/main/java/com/pda/stock/controller/KISController.java
  stock/src/main/java/com/pda/stock/dto/StockChartDto.java
  stock/src/main/java/com/pda/stock/dto/StockChartResponseDto.java
  stock/src/main/java/com/pda/stock/service/KISService.java
Labels: ✨ Feature

#68 [Feat] 동맹 요청 조회 API 구현 #63
  core/src/main/java/com/pda/core/controller/AllianceController.java
  core/src/main/java/com/pda/core/dto/alliance_notice/GetAllianceNoticeListResponseDto.java
  core/src/main/java/com/pda/core/entity/AllianceNotice.java
  core/src/main/java/com/pda/core/repository/AllianceNoticeRepository.java
  core/src/main/java/com/pda/core/service/AllianceService.java
Labels: ✨ Feature

#74 [Fix] 동맹 관련 API 응답 데이터 수정 #71
  core/src/main/java/com/pda/core/dto/alliance/GetTravelerAllianceListResponseDto.java
  core/src/main/java/com/pda/core/entity/AllianceNotice.java
  core/src/main/java/com/pda/core/repository/AllianceNoticeRepository.java
  core/src/main/java/com/pda/core/repository/TravelerAllianceRepository.java
  core/src/main/java/com/pda/core/service/AllianceService.java
Labels: 🐛 fix

#75 [Feat] tutorial 관련 api 구현 및 traveler 엔티티 수정 #69
  core/src/main/java/com/pda/core/controller/TravelerController.java
  core/src/main/java/com/pda/core/dto/HasAccountResponseDto.java
  core/src/main/java/com/pda/core/dto/JoinRequestDto.java
  core/src/main/java/com/pda/core/entity/Traveler.java
  core/src/main/java/com/pda/core/service/TravelerService.java
Labels: ✨ Feature, 🐛 fix

#76 스톡몬 상세 조회 API 전일 종가 추가
  core/src/main/java/com/pda/core/client/StockFeignClient.java
  core/src/main/java/com/pda/core/dto/GetStockmonDetailResponseDto.java
  core/src/main/java/com/pda/core/dto/alliance_notice/AllianceNoticeDto.java
  core/src/main/java/com/pda/core/service/StockmonService.java
  stock/src/main/java/com/pda/stock/controller/KISController.java
  stock/src/main/java/com/pda/stock/dto/StockChartDto.java
  stock/src/main/java/com/pda/stock/service/KISService.java
Labels: ✨ Feature

#78 동맹 목록 조회 API, 모험가 닉네임 검색 API 응답데이터 수정: id -> travelerId로 수정 #77
  core/src/main/java/com/pda/core/dto/GetTravelerNicknameResponseDto.java
  core/src/main/java/com/pda/core/dto/alliance/GetTravelerAllianceListResponseDto.java
  core/src/main/java/com/pda/core/repository/TravelerAllianceRepository.java
Labels: :recycle: refactor

#80 [FIX] 리젠 좌표 이상하게 찍히는 현상 수정
  core/src/main/java/com/pda/core/controller/WorldController.java
  core/src/main/java/com/pda/core/service/WorldService.java
Labels: ✨ Feature

#81 [FIX] 스톡몬 목록 리스트 조회에서 senderNicknmame 가져오는 것 포함
  core/src/main/java/com/pda/core/dto/GetStockmonExchangeListResponseDto.java
  core/src/main/java/com/pda/core/repository/ExchangeNoticeRepository.java
Labels: 🐛 fix

#83 [Fix] 동맹 요청 수락시 해당 요청이 동맹 요청 리스트에서 사라지도록 수정 #82
  core/src/main/java/com/pda/core/service/AllianceService.java
Labels: 🐛 fix

#86 차트 데이터 조회 API 응답 데이터 오름차순으로 정렬
  stock/src/main/java/com/pda/stock/service/KISService.java
Labels: 🐛 fix

#87 [FIX] 교환 수락 후 알림 목록에서 제거하는 부분 추가
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
Labels: 🐛 fix

#89 [FIX] 스톡몬 목록 조회 수정 #88
  core/src/main/java/com/pda/core/dto/GetStockmonExchangeListResponseDto.java
  core/src/main/java/com/pda/core/repository/ExchangeNoticeRepository.java
Labels: 🐛 fix

#90 소켓 연결 관련 에러 수정
  stock/src/main/java/com/pda/stock/controller/StockController.java
  stock/src/main/java/com/pda/stock/service/MyApplicationListener.java
  stock/src/main/java/com/pda/stock/websocket/WebSocketEventListener.java
Labels: 🐛 fix

#92 [FIX] 스톡몬 교환 요청 관련 로직 전부 수정 #91
  core/src/main/java/com/pda/core/controller/ExchangeNoticeController.java
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
Labels: 🐛 fix

#93 스톡몬 교환 수락 후 지우는 함수 추가
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
Labels: 🐛 fix

#96 [Feat] 2배 이벤트 추가
  core/src/main/java/com/pda/core/service/WorldService.java
  core/src/main/java/com/pda/core/utils/WorldConstant.java
  stock/src/main/java/com/pda/stock/client/KISFeignClient.java
Labels: ✨ Feature

#99 [Feat] 스톡볼 감소 API 개발
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/dto/DecreaseCountRequestDto.java
  core/src/main/java/com/pda/core/service/TravelerStockmonService.java
Labels: ✨ Feature

#100 [Feat] 캐싱 적용
  build.gradle
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/controller/WorldController.java
  core/src/main/java/com/pda/core/dto/CatchStockmonRequestDto.java
  core/src/main/java/com/pda/core/dto/DecreaseCountRequestDto.java
  core/src/main/java/com/pda/core/exception/NotEnoughStockmonException.java
  core/src/main/java/com/pda/core/repository/AccountRepository.java
  core/src/main/java/com/pda/core/repository/TravelerStockmonRepository.java
  core/src/main/java/com/pda/core/service/AccountService.java
  core/src/main/java/com/pda/core/service/StockService.java
  core/src/main/java/com/pda/core/service/TravelerStockmonService.java
  core/src/main/java/com/pda/core/service/WorldService.java
  core/src/main/java/com/pda/core/utils/WorldConstant.java
  stock/src/main/java/com/pda/stock/StockApplication.java
  stock/src/main/java/com/pda/stock/config/RedisConfig.java
  stock/src/main/java/com/pda/stock/service/KISService.java
  stock/src/main/resources/application.properties
Labels: ✨ Feature

#102 [Feat] 모험가 보유 주식 조회 기능 구현 #101
  core/src/main/java/com/pda/core/controller/TravelerController.java
  core/src/main/java/com/pda/core/dto/GetTravelerStockListResponseDto.java
  core/src/main/java/com/pda/core/dto/TravelerStockDto.java
  core/src/main/java/com/pda/core/repository/AccountStockRepository.java
  core/src/main/java/com/pda/core/service/StockService.java
Labels: ✨ Feature

#105 [Feat] 각종 에러 수정 및 API 변경 사항 추가
  commons/src/main/java/com/pda/commons/dto/StockInfoDto.java
  core/src/main/java/com/pda/core/client/StockFeignClient.java
  core/src/main/java/com/pda/core/controller/AccountController.java
  core/src/main/java/com/pda/core/dto/AccountStockResponseDto.java
  core/src/main/java/com/pda/core/dto/CatchStockmonResponseDto.java
  core/src/main/java/com/pda/core/repository/TravelerStockmonRepository.java
  core/src/main/java/com/pda/core/service/AccountService.java
  core/src/main/java/com/pda/core/service/StockService.java
  core/src/main/java/com/pda/core/service/TravelerStockmonService.java
  core/src/main/java/com/pda/core/service/WorldService.java
  stock/src/main/java/com/pda/stock/client/KISFeignClient.java
  stock/src/main/java/com/pda/stock/controller/KISController.java
  stock/src/main/java/com/pda/stock/service/KISService.java
Labels: :recycle: refactor, ✨ Feature, 🐛 fix

#106 [Fix] stocktowertimer 로직 수정
  core/src/main/java/com/pda/core/controller/StockTowerTimerController.java
  core/src/main/java/com/pda/core/entity/StockTowerTimer.java
  core/src/main/java/com/pda/core/repository/StockTowerTimerRepository.java
  core/src/main/java/com/pda/core/service/StockTowerTimerService.java
Labels: 🐛 fix

#108 [Feat] 편의성 및 사용성 개선
  core/src/main/java/com/pda/core/dto/StockmonExchangeNoticeRequestDto.java
  core/src/main/java/com/pda/core/dto/TravelerStockmonDto.java
  core/src/main/java/com/pda/core/entity/ExchangeNotice.java
  core/src/main/java/com/pda/core/service/ExchangeNoticeService.java
  core/src/main/java/com/pda/core/service/TravelerStockmonService.java
  core/src/main/java/com/pda/core/service/WorldService.java
  stock/src/main/java/com/pda/stock/service/KISService.java
Labels: ✨ Feature
