Repository StockmonGo/BE, pull requests merged in 2024-08, with the labels that each got.

#4 [Feat] 주변 스톡몬, 스톡타워 조회 틀 API #03
  build.gradle
  commons/src/main/java/com/pda/commons/dto/FailResponse.java
  commons/src/main/java/com/pda/commons/dto/SuccessResponse.java
  commons/src/main/resources/application.properties
  core/src/main/java/com/pda/core/controller/WorldController.java
  core/src/main/java/com/pda/core/dto/GetWorldStockmonsRequestDto.java
  core/src/main/java/com/pda/core/dto/GetWorldStockmonsResponseDto.java
  core/src/main/java/com/pda/core/dto/WorldStockmonDto.java
  core/src/main/java/com/pda/core/entity/Stock.java
  core/src/main/java/com/pda/core/entity/StockTower.java
  core/src/main/java/com/pda/core/entity/StockType.java
  core/src/main/java/com/pda/core/entity/Stockmon.java
  core/src/main/java/com/pda/core/entity/World.java
  core/src/main/java/com/pda/core/exception/CoreException.java
  core/src/main/java/com/pda/core/exception/CoreExceptionHandler.java
  core/src/main/java/com/pda/core/exception/ExceptionMessage.java
  core/src/main/java/com/pda/core/repository/StockRepository.java
  core/src/main/java/com/pda/core/repository/StockTowerRepository.java
  core/src/main/java/com/pda/core/repository/StockTypeRepository.java
  core/src/main/java/com/pda/core/repository/StockmonRepository.java
  core/src/main/java/com/pda/core/repository/WorldRepository.java
  core/src/main/java/com/pda/core/service/StockService.java
  core/src/main/java/com/pda/core/service/StockTowerService.java
  core/src/main/java/com/pda/core/service/StockTypeService.java
  core/src/main/java/com/pda/core/service/StockmonService.java
  core/src/main/java/com/pda/core/service/WorldService.java
  src/main/resources/application.properties
Labels: ✨ Feature

#11 [FIX] 스톡몬 목록 조회 api 수정 #10
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/dto/TravelerStockmonDto.java
  core/src/main/java/com/pda/core/entity/Account.java
  core/src/main/java/com/pda/core/entity/Region.java
  core/src/main/java/com/pda/core/entity/StockTower.java
  core/src/main/java/com/pda/core/entity/Stockmon.java
  core/src/main/java/com/pda/core/entity/Traveler.java
  core/src/main/java/com/pda/core/entity/World.java
  core/src/main/java/com/pda/core/service/TravelerStockmonService.java
Labels: 🐛 fix

#13 [Feat] 모험가 닉네임 검색 기능 구현 #12
  commons/src/main/java/com/pda/commons/dto/FailResponse.java
  core/src/main/java/com/pda/core/controller/TravelerController.java
  core/src/main/java/com/pda/core/controller/TravelerStockmonController.java
  core/src/main/java/com/pda/core/dto/GetTravelerNicknameResponseDto.java
  core/src/main/java/com/pda/core/exception/ExceptionMessage.java
  core/src/main/java/com/pda/core/exception/NoTravelerException.java
  core/src/main/java/com/pda/core/repository/TravelerRepository.java
  core/src/main/java/com/pda/core/service/TravelerService.java
Labels: ✨ Feature

#16 [Feat] Redis 연결
  build.gradle
  core/src/main/java/com/pda/core/config/AppConfig.java
  core/src/main/java/com/pda/core/controller/SwaggerTestController.java
  core/src/main/java/com/pda/core/controller/TravelerController.java
  core/src/main/java/com/pda/core/entity/World.java
  core/src/main/java/com/pda/core/service/RedisService.java
  core/src/main/resources/application.properties
Labels: ✨ Feature

#17 [Feat] 개좌 개설 및 개설 여부 API
  core/src/main/java/com/pda/core/controller/AccountController.java
  core/src/main/java/com/pda/core/controller/TravelerController.java
  core/src/main/java/com/pda/core/dto/AccountCheckResponseDto.java
  core/src/main/java/com/pda/core/dto/AccountDto.java
  core/src/main/java/com/pda/core/dto/CreateAccountRequestDto.java
  core/src/main/java/com/pda/core/entity/Account.java
  core/src/main/java/com/pda/core/entity/Stockmon.java
  core/src/main/java/com/pda/core/exception/ExceptionMessage.java
  core/src/main/java/com/pda/core/exception/HasAccountException.java
  core/src/main/java/com/pda/core/repository/AccountRepository.java
  core/src/main/java/com/pda/core/repository/TravelerRepository.java
  core/src/main/java/com/pda/core/service/AccountService.java
Labels: ✨ Feature

#18 [Feat] 웹 소켓 관련 환경 세팅 및 한국투자증권 소켓 연결 #7
  build.gradle
  stock/build.gradle
  stock/src/main/java/com/pda/stock/entity/Body.java
  stock/src/main/java/com/pda/stock/entity/Header.java
  stock/src/main/java/com/pda/stock/entity/Input.java
  stock/src/main/java/com/pda/stock/entity/Stock.java
  stock/src/main/java/com/pda/stock/entity/StockPriceDto.java
  stock/src/main/java/com/pda/stock/websocket/WebSocketConfig.java
  stock/src/main/java/com/pda/stock/websocket/WebSocketEventListener.java
  stock/src/main/java/com/pda/stock/websocket/WebSocketMessage.java
  stock/src/main/resources/application.properties
Labels: ✨ Feature

#19 [FEAT] 맵 리젠과 생성 및 주변 맵 조회하는 로직 추가
  build.gradle
  core/src/main/java/com/pda/core/CoreApplication.java
  core/src/main/java/com/pda/core/config/RedisConfig.java
  core/src/main/java/com/pda/core/controller/SwaggerTestController.java
  core/src/main/java/com/pda/core/controller/WorldController.java
  core/src/main/java/com/pda/core/dto/GetWorldStockmonsRequestDto.java
  core/src/main/java/com/pda/core/dto/WorldStockmonDto.java
  core/src/main/java/com/pda/core/entity/Stock.java
  core/src/main/java/com/pda/core/entity/World.java
  core/src/main/java/com/pda/core/repository/RedisRepository.java
  core/src/main/java/com/pda/core/service/StockTowerService.java
  core/src/main/java/com/pda/core/service/WorldService.java
  core/src/main/java/com/pda/core/utils/RandomUtils.java
  core/src/main/java/com/pda/core/utils/WorldConstants.java
  core/src/main/resources/application.properties
  stock/src/main/resources/application.properties
Labels: :recycle: refactor, ✨ Feature, 🐛 fix

#20 [Feat] 회원 정보 조회 api 추가
  core/src/main/java/com/pda/core/controller/AccountController.java
  core/src/main/java/com/pda/core/dto/HasAccountResponseDto.java
  core/src/main/java/com/pda/core/service/AccountService.java
  core/src/main/java/com/pda/core/service/TravelerService.java
Labels: ✨ Feature

#24 [FEAT] 주변 스톡몬, 스톡타워 조회 API 중 주변 스톡타워 조회 기능 추가
  core/src/main/java/com/pda/core/entity/StockTower.java
  core/src/main/java/com/pda/core/entity/World.java
  core/src/main/java/com/pda/core/repository/StockTowerRepository.java
  core/src/main/java/com/pda/core/service/RedisService.java
  core/src/main/java/com/pda/core/service/StockTowerService.java
  core/src/main/java/com/pda/core/service/WorldService.java
Labels: :recycle: refactor, ✨ Feature, 🐛 fix
